//! The calm splash shown while nothing is presenting (no driver yet, or SteamVR not drawing).
//!
//! The picture is a flat dark background with one small block (two lens shapes and the line "Waiting for SteamVR") in the middle of
//! each eye's half. The block is a coverage patch generated by `splash/make_splash.py` and embedded here. Both halves get the same
//! bytes at the same place, so the splash has no disparity and no per-eye colour difference. Everything here is plain arithmetic;
//! the Vulkan recording is in `main.rs`.

/// Grey level (0-255, as written to the swapchain) of the background and of the mark at full coverage. Tuned for comfort, not for
/// visibility: low contrast on purpose.
pub const BACKGROUND: u8 = 8;
pub const MARK: u8 = 70;
/// How long the picture takes to rise from black, in seconds.
pub const FADE_SECS: f32 = 1.0;

const COVERAGE: &[u8] = include_bytes!("../splash/splash.raw");
const SIZE: &str = include_str!("../splash/splash.size");

/// The coverage patch (one byte per pixel, rows top to bottom) with its width and height.
pub fn patch() -> (&'static [u8], u32, u32) {
    let mut n = SIZE.split_whitespace().map(|v| v.parse::<u32>().expect("splash.size holds two numbers"));
    (COVERAGE, n.next().expect("splash width"), n.next().expect("splash height"))
}

/// Brightness factor 0..=1 for the time since the splash started showing: 0 at the first frame, smoothstep up to 1 over `FADE_SECS`.
pub fn fade_level(elapsed_secs: f32) -> f32 {
    let x = (elapsed_secs / FADE_SECS).clamp(0.0, 1.0);
    x * x * (3.0 - 2.0 * x)
}

/// The byte written for a grey `value` at fade `level`.
fn scaled(value: f32, level: f32) -> u8 {
    (value * level).round().clamp(0.0, 255.0) as u8
}

/// The background's byte at `level`; the clear colour and the patch's uncovered pixels use the same value, so the patch has no visible edge.
pub fn background_byte(level: f32) -> u8 {
    scaled(BACKGROUND as f32, level)
}

/// Write the patch at `level` as grey 4-byte pixels (equal colour channels, opaque), so the byte order of the swapchain format does not matter.
pub fn scale_patch(coverage: &[u8], level: f32, out: &mut [u8]) {
    assert_eq!(out.len(), coverage.len() * 4, "the staging buffer holds four bytes per patch pixel");
    for (c, px) in coverage.iter().zip(out.chunks_exact_mut(4)) {
        let v = scaled(BACKGROUND as f32 + (MARK as f32 - BACKGROUND as f32) * *c as f32 / 255.0, level);
        px.copy_from_slice(&[v, v, v, 255]);
    }
}

/// Top-left corner of the patch in each half of a `width` x `height` image: centred in the left half and in the right half.
pub fn offsets(width: u32, height: u32, patch_w: u32, patch_h: u32) -> [(i32, i32); 2] {
    let half = width / 2;
    let x = (half.saturating_sub(patch_w) / 2) as i32;
    let y = (height.saturating_sub(patch_h) / 2) as i32;
    [(x, y), (half as i32 + x, y)]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_first_frame_is_black_and_the_fade_ends_at_full_level() {
        assert_eq!(fade_level(0.0), 0.0);
        assert_eq!(fade_level(-1.0), 0.0);
        assert_eq!(fade_level(FADE_SECS), 1.0);
        assert_eq!(fade_level(60.0), 1.0);
    }

    #[test]
    fn the_fade_rises_without_going_back() {
        let mut last = 0.0;
        for i in 0..=120 {
            let l = fade_level(i as f32 / 60.0);
            assert!(l >= last, "level fell at step {i}");
            last = l;
        }
    }

    #[test]
    fn scaling_at_zero_is_black_and_at_one_is_the_configured_levels() {
        let cov = [0u8, 255, 128];
        let mut out = [9u8; 12];
        scale_patch(&cov, 0.0, &mut out);
        assert!(out.chunks(4).all(|p| p == [0, 0, 0, 255]));
        scale_patch(&cov, 1.0, &mut out);
        assert_eq!(&out[0..4], &[BACKGROUND, BACKGROUND, BACKGROUND, 255]);
        assert_eq!(&out[4..8], &[MARK, MARK, MARK, 255]);
        assert!(out[8] > BACKGROUND && out[8] < MARK);
        assert_eq!(background_byte(1.0), BACKGROUND);
        assert_eq!(background_byte(0.0), 0);
    }

    #[test]
    fn uncovered_patch_pixels_match_the_background_at_every_level() {
        for i in 0..=20 {
            let l = i as f32 / 20.0;
            let mut out = [0u8; 4];
            scale_patch(&[0], l, &mut out);
            assert_eq!(out[0], background_byte(l));
        }
    }

    #[test]
    fn both_halves_place_the_patch_at_the_same_spot_within_their_half() {
        let [l, r] = offsets(3840, 1080, 640, 160);
        assert_eq!(l, (640, 460));
        assert_eq!(r.0 - 1920, l.0);
        assert_eq!(r.1, l.1);
    }

    #[test]
    fn the_embedded_patch_matches_its_size() {
        let (data, w, h) = patch();
        assert_eq!(data.len(), (w * h) as usize);
        assert!(data.iter().any(|&c| c == 255) && data.contains(&0));
    }
}
